# load("@aspect_rules_js//js:defs.bzl", "js_run_devserver)
# load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

# js_run_devserver(
#     name = "devserver",
#     bootstrap = ["@npm_bazel_typescript//:protobufjs_bootstrap_scripts"],
#     entry_module = "bootcamp/typescript/app",
#     port = 8080,
#     deps = [":app"],
# )
